### PR TITLE
WIP : Add support for Camera Control

### PR DESCRIPTION
**Pull request by lbegani**
This change is to enable users to controls the camera parameters. 
- Details on how the camera parameters will be exposed by the camera(drone) to ground  control station, how GCS will communicate with drone to set/get camera params can be found here - http://discuss.px4.io/t/mavlink-camera-api-discussion/3278/31. 
- Changes on the QGC for this feature can be found here - https://github.com/mavlink/qgroundcontrol/tree/cameraControl

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Please run this through clang-format to fix the coding style and make it easier to read.

Splitting the commit into smaller parts make it easier to review.

Write am explanation message on the commit.

**Comment by lbegani** [comment]
@lucasdemarchi I have fixed the format using clang-format now. Should I split the commit or is it acceptable?

**Comment by anselmolsm** [comment]
Please split.

**Comment by lbegani** [comment]
Opened a separate pull request with multiple commits - https://github.com/01org/camera-streaming-daemon/pull/83

**Pull request closed without merging**
