### PR TITLE
Add systemd service file

### PR DESCRIPTION
**Pull request by Rjasuja**
Adding systemd service file to support systemd initialization manager.

Issue: #36
Test: Verified service on Ubuntu

Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>

### CODE REVIEW

**Comment by Rjasuja** [comment]
@lucasdemarchi made the changes as requested.
@otaviobp i have made changes for this PR in .gitignore and configure.ac(remove systemdsystemunirdir output variable creation).

**Comment by lucasdemarchi** [comment]
@Rjasuja the binary is csd not camera-streaming-daemon. You mention in the commit message you tested it on your machine. Did you test it actually work or just that it was generating the service file?

**Comment by lucasdemarchi** [comment]
I fixed the issue and pushed. Going forward, here are some rules:

  - It's assumed that once you submitted the PR it's tested. You don't need to mention it on the commit message, it's pretty useless on the git history
  - This project doesn't use signed-of-by, so no need to add it to the commit message
  - You don't need to mention the issue on the commit message. If you want that the issue on github is automatically closed, you can mention the issue on the PR rather than on the commit message.

Thanks

**Comment by Rjasuja** [comment]
I tested the service by running it but not on my system. I did the binary name change in other system, just missed changing it in mine.. Apologise for the miss.

**Pull request closed without merging**
